---
title: "Course materials"
format: 
  html:
    toc: true
---

Coming soon!

# Day 1

## Morning

1. [Lecture 1: Prediction models in medicine, Michael Sachs (pdf)](/data/lectures/day1-lecture1.pdf)
2. [Lecture 2: Medical risk prediction models, Thomas Gerds (pdf)](/data/lectures/day1-lecture2.pdf)
3. [Exercise 1: The Steno Risk engine](/data/exercises/day1-morning.qmd)
    - [Solutions](/data/exercises/day1-morning-with-solution.qmd)


## Afternoon

1. [Lecture 3: Obstacles and pitfalls, Thomas Gerds (pdf)](/data/lectures/day1-lecture3.pdf)
2. [Lecture 4: Learning algorithms and validation, Michael Sachs (pdf)](/data/lectures/day1-lecture4.pdf)
3. [Exercise 2: Developing and validating your own models](/data/exercises/day1-afternoon.qmd)
4. [Lecture 5: Introduction to causal prediction, Ruth Keogh (pdf)](/data/lectures/day1-lecture5.pdf)

# Day 2

## Morning

1. [Lecture 6: Introduction to causal inference, Erin Gabriel (pdf)](/data/lectures/day2-lecture1.pdf)
2. [Exercise 3: Causal DAGs](/data/exercises/day2-morning.qmd)

## Afternoon

1. [Lecture 7: Estimands for causal prediction, Nan van Geloven (pdf)](/data/lectures/day2-afternoon-estimands.pdf)
2. [Exercise 4: Estimands for causal prediction, Nan van Geloven](/data/exercises/day2-afternoon.qmd)
    - [Solutions (docx)](/data/exercises/day2-afternoon-practical_SOLUTIONS.docx)

# Day 3


## Morning

1. [Lecture 8: Estimation, Karla Diaz-Ordaz (pdf)](/data/lectures/EstimationLecture_KPH_shortcourse_causalpred_v1.pdf)
2. [Exercise 5: Estimation](/data/exercises/day3-morning.qmd)
    - [Solution](/data/exercises/day3-morning-solutions.qmd)

## Afternoon

1. [Lecture 9: Evaluation, Nan van Geloven (pdf)](/data/lectures/day3-afternoon-lecture.pdf)
2. [Exercise 6: Evaluation](/data/exercises/day3-afternoon.qmd)
    - [Solutions](/data/exercises/day3-afternoon-solution.qmd)

# Day 4


## Morning

1. [Lecture 10: Time to event outcomes and strategies, Ruth Keogh (pdf)](/data/lectures/causalpred_RK_Day4_morning.pdf)


## Afternoon




